
package com.sltc.soa.client.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DemoWS", targetNamespace = "http://soa.sltc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DemoWS {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convert", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.Convert")
    @ResponseWrapper(localName = "convertResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.ConvertResponse")
    @Action(input = "http://soa.sltc.com/DemoWS/convertRequest", output = "http://soa.sltc.com/DemoWS/convertResponse")
    public float convert(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "database", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.Database")
    @ResponseWrapper(localName = "databaseResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.DatabaseResponse")
    @Action(input = "http://soa.sltc.com/DemoWS/databaseRequest", output = "http://soa.sltc.com/DemoWS/databaseResponse")
    public float database(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
